//pin-configuration-board-v2.h
#ifndef __PIN_CONFIGURATION_BOARD_V2_H__
#define __PIN_CONFIGURATION_BOARD_V2_H__

#define MIDI_OUT_PIN 	10
#define GATE_PIN 		11
#define CLOCK_OUT_PIN 	13

#define MATRIX_WRITE_EXTERNAL_PIN 2
const short int WRITE_MUX_ADDRESS_PINS[] = {3,4,5};
#define READ_MUX_OUT_VALUE_PIN 6
const short int READ_MUX_ADDRESS_PINS[] = {7, 8, 9};	

#define ARPEGGIATOR_ENABLE_MODE_PIN 		17
#define ARPEGGIATOR_FUNCTION_MODE_PIN 		16
#define ARPEGGIATOR_OCTAVE_EXTENSION_PIN 	15
#define ARPEGGIATOR_CLOCK_RATE_PIN 			14
#define ARPEGGIATOR_CLOCK_OUT_PIN 			13
#define ARPEGGIATOR_CLOCK_IN_PIN 			12

#define SEQUENCER_PIN 20

#endif
